[program:horizon]
process_name=%(program_name)s
command=php /var/www/klaz.safe-pay.to/klaz-safe-pay-master/artisan horizon
autostart=true
autorestart=true
user=root
redirect_stderr=true
stdout_logfile=/var/www/klaz.safe-pay.to_horizon.log
stopwaitsecs=3600
